
title: Learn To Groove
email: matt@learntogroove.com
description: > # this means to ignore newlines until "baseurl:"
  Learn To Groove: Your Guide To Rock Solid Rhythm
  Exercises and turorials to explore the primal essence of musical expression. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://learntogroove.com" # the base hostname & protocol for your site
twitter_username: LifeOnDrums
github_username:  MattCordier
timezone: America/Chicago
sass:
  sass_dir: public/_scss
  style: compressed
# Build settings
markdown: kramdown
theme: minima
